// src/routes/components/navbar/index.svelte
<script lang="ts">
	import {
		BookOpenOutline,
		HeartOutline,
		ShoppingBagOutline,
		CartOutline
	} from 'flowbite-svelte-icons';
	import { Tooltip } from 'flowbite-svelte';
	import Sidebar from './Sidebar.svelte';
	import { globalStore } from 'store';
	import { Badge } from 'components';

	let showSidebar = $state({ active: false });

	const navItemStyles =
		'flex-1 text-center focus:outline-dark text-xs font-semibold md:text-sm text-dark';
</script>

{#snippet navlink({
	to,
	Icon,
	label,
	indicator,
	fill = 'hotpink'
}: {
	to: string;
	Icon: typeof BookOpenOutline;
	label: string;
	indicator: number;
	fill?: string;
})}
	<a href={to} class={navItemStyles}>
		<Badge {indicator} class="text-dark w-full">
			<span class="flex flex-col items-center">
				<Icon {fill} class={['w-7 md:w-8', `fill-${fill}`]} />
				{label}
			</span>
		</Badge>
	</a>
{/snippet}

<Sidebar {showSidebar} />
<nav
	id="root-navbar"
	class="flex fixed z-20 left-0 bottom-0 w-full bg-white text-dark items-center p-1 border-t-2 border-secondary shadow-lg shadow-dark"
>
	{@render navlink({
		to: '/checkout',
		indicator: globalStore.shoppingCart.length,
		label: 'Checkout',
		Icon: ShoppingBagOutline
	})}

	{@render navlink({
		to: '/purchaseHistory',
		indicator: globalStore.history.length,
		label: 'History',
		Icon: BookOpenOutline,
		fill: 'primary'
	})}

	<!-- <UserBtn isSignedIn={!!user} /> -->
        <a href="/foo">Foo</a>

	<Badge
                tooltipLabel="Show Shopping Cart"
		class={['text-dark w-full', navItemStyles]}
		onclick={() => (showSidebar.active = true)}
		id="sidebarButton"
		aria-expanded={showSidebar.active}
		aria-controls="sidebar"
		aria-label="Show shopping cart items"
		indicator={globalStore.shoppingCart.length}
	>
		<span class="flex flex-col items-center">
			<CartOutline class="fill-primary w-7 md:w-8" />
			My Cart
		</span>
	</Badge>

	{@render navlink({
		to: '/wishList',
		indicator: globalStore.wishList.length,
		label: 'Wish List',
		Icon: HeartOutline
	})}
</nav>

// app/Components/Navbar.tsx
import { currentUser } from "@clerk/nextjs";
import { HeartIcon, ShoppingCartIcon } from "@heroicons/react/24/outline";
import dynamic from "next/dynamic";
import Link from "next/link";

const UserBtn = dynamic(() => import("./UserBtn"), { ssr: false });

export default async function Navbar() {
  const user = await currentUser();

  return (
    <nav className="flex fixed z-20 left-0 right-0 bottom-6 shadow-lg border-secondary border-2 shadow-dark text-dark bg-light justify-around items-center rounded-lg w-2/3 md:w-96 h-14 md:h-20 md:text-secondary-dark m-auto">
      <Link
        href={user ? "/shoppingCart" : "/sign-in"}
        className="outline-dark flex flex-col items-center"
      >
        <ShoppingCartIcon className="fill-primary" width={50} />
        <p className="hidden md:block">My Cart</p>
      </Link>

      <UserBtn isSignedIn={!!user} />

      <Link
        href={user ? "/wishList" : "/sign-in"}
        className="text-center flex flex-col items-center"
      >
        <HeartIcon width={50} fill="hotpink" />
        <p className="hidden md:block">My Wish List</p>
      </Link>
    </nav>
  );
}
