// app/Components/Navbar/index.tsx
"use client";

import useGlobalStore from "@/lib/store";
import {
  BookOpenIcon, HeartIcon,
  ShoppingBagIcon,
  ShoppingCartIcon
} from "@heroicons/react/24/outline";
import { Badge } from "@mui/material";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useState } from "react";
import { Button, TooltipTrigger } from "react-aria-components";
import TooltipWrapper from "../TooltipWrapper";
import Sidebar from "./Sidebar";

const UserBtn = dynamic(() => import("../UserBtn"), { ssr: false });

export default function Navbar() {
  const [showSideBar, setShowSideBar] = useState(false),
    { currentUser: { purchaseHistory, shoppingCart, user, wishList } } = useGlobalStore();

  // get objects in history
  let historyCount = 0
  if (purchaseHistory)
    Object.keys(purchaseHistory).forEach(date => {
      historyCount += purchaseHistory[date].length
    })

  return (
    <>
      <Sidebar showSideBar={showSideBar} setShowSideBar={setShowSideBar} />
      <nav
        id="root-navbar"
        className="flex fixed z-20 left-0 bottom-0 w-full bg-white items-center p-1 border-t-2 border-secondary shadow-lg shadow-dark"
      >
        <Link
          href="/checkout"
          className="flex-1 text-center focus:outline-dark flex flex-col items-center text-xs font-semibold md:text-sm"
        >
          <Badge
            badgeContent={shoppingCart?.length || 0}
            color="primary"
            className="flex flex-col items-center"
          >
            <ShoppingBagIcon className="fill-pink-600 w-7 md:w-8" />
            <p>Checkout</p>
          </Badge>
        </Link>

        <Link
          href="/purchaseHistory"
          className="flex-1 text-center focus:outline-dark flex flex-col items-center text-xs font-semibold md:text-sm"
        >
          <Badge
            badgeContent={historyCount}
            color="primary"
            className="flex flex-col items-center"
          >
            <BookOpenIcon className="fill-primary w-7 md:w-8" />
            <p>History</p>
          </Badge>
        </Link>

        <UserBtn isSignedIn={!!user} />

        <TooltipTrigger>
          <Button
            onPress={() => setShowSideBar(true)}
            className="outline-dark flex-1 text-xs font-semibold md:text-sm"
          >
            <Badge
              badgeContent={shoppingCart?.length || 0}
              color="primary"
              className="flex flex-col items-center"
            >
              <ShoppingCartIcon className="fill-primary w-7 md:w-8" />
              <p>My Cart</p>
            </Badge>
          </Button>
          <TooltipWrapper>Show Shopping Cart</TooltipWrapper>
        </TooltipTrigger>

        <Link
          href="/wishList"
          className="flex-1 text-center focus:outline-dark flex flex-col items-center text-xs font-semibold md:text-sm"
        >
          <Badge
            badgeContent={wishList?.length || 0}
            color="primary"
            className="flex flex-col items-center"
          >
            <HeartIcon fill="hotpink" className="w-7 md:w-8" />
            <p>Wish List</p>
          </Badge>
        </Link>
      </nav>
    </>
  );
}

// src/routes/components/navbar/index.svelte
<script lang="ts">
	import {
		BookOpenOutline,
		HeartOutline,
		ShoppingBagOutline,
		CartOutline
	} from 'flowbite-svelte-icons';
	import { Tooltip } from 'flowbite-svelte';
	import Sidebar from './Sidebar.svelte';
	import { globalStore } from 'store';
	import { Badge } from 'components';

	let showSidebar = $state({ active: false });

	// get objects in history
	let shoppingCart = $derived(
		Object.values(globalStore.products).filter(({ isInCart }) => isInCart)
	);
	let history = $derived(
		Object.values(globalStore.products).filter(({ isPurchased }) => isPurchased)
	);
	const navItemStyles =
		'flex-1 text-center focus:outline-dark text-xs font-semibold md:text-sm text-dark';
</script>

{#snippet navlink({
	to,
	Icon,
	label,
	indicator,
	fill = 'hotpink'
}: {
	to: string;
	Icon: typeof BookOpenOutline;
	label: string;
	indicator: number;
	fill?: string;
})}
	<a href={to} class={navItemStyles}>
		<Badge {indicator} class="text-dark w-full">
			<span class="flex flex-col items-center">
				<Icon {fill} class={['w-7 md:w-8', `fill-${fill}`]} />
				{label}
			</span>
		</Badge>
	</a>
{/snippet}

<Sidebar {showSidebar} />
<nav
	id="root-navbar"
	class="flex fixed z-20 left-0 bottom-0 w-full bg-white text-dark items-center p-1 border-t-2 border-secondary shadow-lg shadow-dark"
>
	{@render navlink({
		to: '/checkout',
		indicator: shoppingCart.length,
		label: 'Checkout',
		Icon: ShoppingBagOutline
	})}

	{@render navlink({
		to: '/purchaseHistory',
		indicator: history.length,
		label: 'History',
		Icon: BookOpenOutline,
		fill: 'primary'
	})}

	<!-- <UserBtn isSignedIn={!!user} /> -->
	Foo

	<Badge
		class={['text-dark w-full', navItemStyles]}
		onclick={() => (showSidebar.active = true)}
		id="sidebarButton"
		aria-expanded={showSidebar.active}
		aria-controls="sidebar"
		aria-label="Show shopping cart items"
		indicator={shoppingCart.length}
	>
		<span class="flex flex-col items-center">
			<CartOutline class="fill-primary w-7 md:w-8" />
			My Cart
		</span>
	</Badge>
	<Tooltip>Show Shopping Cart</Tooltip>

	{@render navlink({
		to: '/wishList',
		indicator: history.length,
		label: 'Wish List',
		Icon: HeartOutline
	})}
</nav>
